import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { Product, SiteSettings } from '../../types';
import { productsRepository } from '../../services/repositories/products.repository';
import { settingsRepository } from '../../services/repositories/settings.repository';
import { Dashboard } from './components/Dashboard';
import { ProductsSection } from './components/ProductsSection';
import { SettingsForm } from './components/SettingsForm';

type Tab = 'dashboard' | 'products' | 'settings';
const emptySettings: SiteSettings = { bannerUrl: '/banner.jpg' };
export function AdminPanel() {
  const [authenticated, setAuthenticated] = useState(() => Boolean(localStorage.getItem('adminUser')));
  const [tab, setTab] = useState<Tab>('dashboard');
  const [editing, setEditing] = useState<Partial<Product> | null>(null);
  const client = useQueryClient();
  const products = useQuery({ queryKey: ['products'], queryFn: () => productsRepository.list(), enabled: authenticated });
  const settings = useQuery({ queryKey: ['settings', 'global'], queryFn: async () => (await settingsRepository.get('global')) ?? emptySettings, enabled: authenticated });
  const invalidate = () => client.invalidateQueries({ queryKey: ['products'] });
  const saveProduct = useMutation({ mutationFn: (product: Product) => productsRepository.save(product), onSuccess: () => { invalidate(); setEditing(null); } });
  const deleteProduct = useMutation({ mutationFn: productsRepository.remove, onSuccess: invalidate });
  const saveSettings = useMutation({ mutationFn: (value: SiteSettings) => settingsRepository.save(value), onSuccess: () => client.invalidateQueries({ queryKey: ['settings'] }) });
  if (!authenticated) return <Login onLogin={() => setAuthenticated(true)} />;
  const loading = products.isLoading || settings.isLoading;
  return <div className="min-h-screen bg-gray-50 md:flex"><aside className="bg-white border-r p-5 md:w-64"><h1 className="text-xl font-bold mb-8">AdminPanel</h1>{(['dashboard', 'products', 'settings'] as Tab[]).map((item) => <button key={item} onClick={() => setTab(item)} className={`block w-full text-left px-3 py-3 rounded-lg capitalize ${tab === item ? 'bg-akari-orange text-white' : ''}`}>{item === 'products' ? 'Inventario' : item === 'settings' ? 'Configuración' : 'Dashboard'}</button>)}<a href="#" className="block mt-8 text-sm">Ver tienda</a><button className="mt-3 text-sm text-red-600" onClick={() => { localStorage.removeItem('adminUser'); setAuthenticated(false); }}>Salir</button></aside><main className="flex-1 p-6 md:p-10"><h2 className="text-2xl font-bold capitalize mb-6">{tab === 'products' ? 'Inventario' : tab === 'settings' ? 'Configuración del sitio' : 'Visión general'}</h2>{loading ? <div>Cargando…</div> : <>{tab === 'dashboard' && <Dashboard products={products.data ?? []} />}{tab === 'products' && <ProductsSection products={products.data ?? []} onEdit={setEditing} onDelete={(id) => { if (confirm('¿Eliminar este producto?')) deleteProduct.mutate(id); }} />}{tab === 'settings' && <SettingsForm settings={settings.data ?? emptySettings} onSave={(value) => saveSettings.mutateAsync(value)} />}</>}</main>{editing && <ProductEditor initial={editing} onClose={() => setEditing(null)} onSave={(draft) => saveProduct.mutate(draft)} />}</div>;
}
function Login({ onLogin }: { onLogin: () => void }) { const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); return <form className="min-h-screen grid place-items-center p-4" onSubmit={(e) => { e.preventDefault(); if (username === 'Admin' && password === '1234') { localStorage.setItem('adminUser', JSON.stringify({ username })); onLogin(); } else setError('Credenciales incorrectas'); }}><div className="bg-white p-8 rounded-2xl shadow w-full max-w-sm space-y-4"><h1 className="text-2xl font-bold">Acceso administrativo</h1>{error && <p className="text-red-600">{error}</p>}<input className="border p-3 w-full" placeholder="Usuario" value={username} onChange={(e) => setUsername(e.target.value)} /><input className="border p-3 w-full" placeholder="Contraseña" type="password" value={password} onChange={(e) => setPassword(e.target.value)} /><button className="w-full bg-akari-orange text-white p-3 rounded">Ingresar</button></div></form>; }
function ProductEditor({ initial, onClose, onSave }: { initial: Partial<Product>; onClose: () => void; onSave: (product: Product) => void }) { const [draft, setDraft] = useState<Partial<Product>>(initial); const change = (key: keyof Product, value: string | number | boolean) => setDraft({ ...draft, [key]: value }); return <div className="fixed inset-0 bg-black/40 grid place-items-center p-4"><form className="bg-white rounded-2xl p-6 w-full max-w-xl space-y-3" onSubmit={(e) => { e.preventDefault(); onSave({ id: draft.id ?? crypto.randomUUID(), name: draft.name ?? '', price: Number(draft.price) || 0, inventory: Number(draft.inventory) || 0, category: draft.category ?? '', image: draft.image ?? '', description: draft.description ?? '', featured: Boolean(draft.featured) }); }}><h2 className="text-xl font-bold">{draft.id ? 'Editar producto' : 'Nuevo producto'}</h2>{(['name', 'category', 'image', 'description'] as const).map((key) => <input key={key} required className="w-full border rounded p-2" placeholder={key} value={draft[key] ?? ''} onChange={(e) => change(key, e.target.value)} />)}<input required type="number" className="w-full border rounded p-2" placeholder="Precio" value={draft.price ?? ''} onChange={(e) => change('price', Number(e.target.value))} /><input required type="number" className="w-full border rounded p-2" placeholder="Stock" value={draft.inventory ?? ''} onChange={(e) => change('inventory', Number(e.target.value))} /><label><input type="checkbox" checked={Boolean(draft.featured)} onChange={(e) => change('featured', e.target.checked)} /> Destacado</label><div className="flex justify-end gap-3"><button type="button" onClick={onClose}>Cancelar</button><button className="bg-akari-orange text-white rounded px-4 py-2">Guardar</button></div></form></div>; }

